services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333" # For REST API
      - "6334:6334" # For gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage 